name: Build and Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Website
        run: npm run build

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Install Nginx
        run: |
          choco install nginx

      - name: Copy Website Files
        run: |
          # Assuming your build files are in the 'build' directory
          cp -r ./build/* /path/to/nginx/html

      - name: Start Nginx
        run: |
          net start nginx

      - name: Deploy Complete
        run: |
          echo "Website deployed successfully!"
