name: Angular Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.x'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Application
        run: npm run build --prod

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Install Nginx
        run: |
          choco install nginx --ignore-checksums
      - name: Copy Angular Build Files to Nginx HTML Directory
        run: |
          cp -r ./dist/* /C:/actions-runner/_work/grc_froend_test/grc_froend_test/dist/grc/browser
      - name: Start Nginx
        run: |
          Start-Service nginx
      - name: Deploy Complete
        run: |
          echo "Angular application deployed successfully!"
