name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod  # Use npm script to build the Angular app in production mode

      - name: Install NGINX
        run: |
          choco install nginx --version 1.24.0 -y  # Install specific version of NGINX using Chocolatey
          Start-Service nginx  # Start NGINX service

      - name: Configure NGINX
        run: |
          $nginxConfigPath = 'C:\nginx\conf\nginx.conf'
          $nginxConfig = @"
          user nginx;
          worker_processes auto;

          events {
            worker_connections 1024;
          }

          http {
            include mime.types;
            default_type application/octet-stream;
            sendfile on;
            keepalive_timeout 65;

          server {
            listen 80;
            server_name localhost;

            location / {
              root C:/path/to/angular/app/dist;  # Update path to your Angular app build output
              index index.html index.htm;
              try_files $uri $uri/ /index.html;
            }
          }
          "@
          Set-Content -Path $nginxConfigPath -Value $nginxConfig -Force

          # Reload NGINX configuration
          nginx -s reload

      - name: Deploy to Windows server
        uses: appleboy/ssh-action@v3  # Use a valid version of the SSH/SCP action
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir C:\nginx\www  # Create directory if not exist
            scp -r dist/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:C:/nginx/www/  # Upload Angular app files to server
