name: Build and Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.x'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: ng build --configuration=production

  deploy:
    runs-on: windows-latest
    
    needs: build

    steps:
      - name: Deploy to Local Web Server
        run: |
          # Start a local web server to host the Angular application
          # Example: ng serve --port 4200
          ng serve --port 4200 &

          # Install ngrok
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

          # Expose the local web server to the internet using ngrok
          ./ngrok http 4200

          # Capture the ngrok URL and use it for further processing or logging

