name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: self-hosted  # Specify the self-hosted runner
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 18.14.2
        uses: actions/setup-node@v3
        with:
          node-version: '18.14'

      - name: Install dependencies and build
        run: |
          # Replace these commands with your build commands
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/grc_froend_test
          publish_branch: gh-pages
          cname: puneethre.github.io





    









