name: Angular CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.14'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app for localhost
      run: npm run build -- --prod --base-href=/ --output-path=dist/local

    - name: Serve Angular app locally
      run: npm run start -- --port 4200 --disable-host-check

    - name: Build Angular app for GitHub Pages
      run: npm run build -- --prod --base-href=/github-pages/ --output-path=dist/github-pages

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist/github-pages






