name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: self-hosted  # Use the latest version of Ubuntu as the runner
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 18.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 18.14

      - name: Install dependencies and build
        run: |
          # Replace these commands with your build commands
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Specify the directory containing your built assets

      - name: Install Nginx
        run: sudo apt-get update && sudo apt-get install -y nginx

      - name: Configure Nginx
        run: |
          sudo rm /etc/nginx/sites-available/default
          sudo touch /etc/nginx/sites-available/default
          sudo chmod 777 /etc/nginx/sites-available/default
          echo "server {
                  listen 80;
                  server_name your_domain.com;
                  root /path/to/your/build/directory;  # Replace this with the path to your build directory
                  index index.html;
                  location / {
                      try_files $uri $uri/ /index.html;
                  }
              }" > /etc/nginx/sites-available/default
          sudo nginx -t
          sudo systemctl restart nginx









