name: Angular Build and Deploy

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build:
    runs-on: window-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Angular App
        run: npm run build -- --prod
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # Change this to your branch name if different
          FOLDER: C:\actions-runner/dist  # Adjust this if your build output is different



