name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: window-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14  # Adjust to the appropriate Node.js version for your project

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --prod --base-href=/angular-github-actions/  # Adjust base-href according to your GitHub Pages URL

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/angular-github-actions
          enable_jekyll: true  # Change to false if you're not using Jekyll







